### ISSUE TITLE
[★★★★★] 테스트 문항들 불러오기 / 결과 계산 및 저장하기

### ISSUE THREAD

**Issue by rebi13** [MBTI-Inside/todo#5]
테스트 페이지 접근 시 문항들을 조회합니다.

문항은 기본적으로 16문항을 가져오려 합니다. (8의 배수)

문항 컬렉션에 있는 데이터들 중 mbtiType이 E인 문항 2개 랜덤 선택, I인 문항 2개 랜덤 선택 ... J인 문항 2개 랜덤 선택, P인 문항 2개 랜덤 선택

해당 16문항은 표시되는 순서도 뒤죽박죽이어야 합니다. (E-I-N-S-T-F-J-P 같이 순서대로 가는 형태 x)

---------

결과 데이터 계산은 코드를 구성해보고 다시 얘기해봐야 할 것 같지만 (앞단에서 처리할 지, 뒷단에서 처리할 지)

골자는 다음과 같습니다.

예를 들어 해당 문항에서 E에 대한 문항을 선택했다고 가정합시다. (남은 얘기는 만나서 해야징)

```
"subject": "바쁜 회사 생활을 보낸 당신. 황금 같은 주말을 어떻게 보내려고 할까?",
 "answer": {
    "I": "주중 회사(실외)였으니 주말엔 집에서 쉬어야지~",
    "E": "주중 회사(실내)였으니 주말엔 밖에 나가서 놀아야지!"
 },
"mbtiType": "E",
"proportion": 68
```

E에 대해서 68의 비중이 있으므로 현재 E와 I (에너지) 유형에 대한 비중은 68 : 0 입니다.
문항 유형이 E이고, 해당 유형에 대한 비중도가 68이기 때문입니다.

그럼 다음 문항에서 또 E에 대한 문항을 선택했다면?
```
"subject": "내가 더 잘 알고 있는 것은?",
 "answer": {
    "E": "상대방을 기분 좋게 하는 방법 :D",
    "I": "상대방을 기분 나쁘지 않게 배려하는 방법 :)"
 },
 "mbtiType": "I",
 "proportion": 60
```

I에 대해서 60의 비중이 있으므로 E에 대한 비중은 40입니다 (100 - 60)
따라서 E와 I (에너지) 유형에 대한 비중은 68 : 0, 40 : 0 => 108 : 0 입니다.

2개의 문항에 대해 에너지 유형에 대한 비율을 계산한다면?

E의 비율 : (E / E + I) * 100 = 100
I의 비율 : (I / E + I) * 100 = 0

해당 계산식을 통해 결과 데이터가 도출될 것입니다.

**Comment by MCprotein** [comment]
@rebi13 
데이터 구조를 아래와 같이 변경하는것은 어떠신가요?
```json
{
  "subject": "바쁜 회사 생활을 보낸 당신. 황금 같은 주말을 어떻게 보내려고 할까?",
  "answer" [
    {
      "type": "I",
      "select": "주중 회사(실외)였으니 주말엔 집에서 쉬어야지~",
      "proportion": 60
    },
    {
      "type": "E",
      "select": "주중 회사(실내)였으니 주말엔 밖에 나가서 놀아야지!",
      "proportion": 40
    }
  ],
  "type": "energy_direction"
}
```

![image](https://github.com/MBTI-Inside/todo/assets/89785501/e9273162-9c67-4835-9223-7cba01bbef50)


이렇게 말슴드리는 이유는 아래와 같습니다
1. 데이터의 key는 value의 타입이여야 하는데, 말씀하신거에서는 key가 value로 사용되고 있습니다 이렇게 사용하면 구조가 유연하지 않고 인덱스가 필요한 경우에 쿼리 인덱싱에 적합하지 않습니다 mongodb 여서 이렇게 작성하신거같은데 rdb에서 table column field에 이렇게 value를 넣지 않는것을 생각하시면 편할거같습니다
2. proportion을 각각 지정하지 않으면 선택할때마다 계산해야되는데, 이것보다는 저장해놓고 갖다쓰는게 더 간편할거같습니다
3. mbti는 I or E, F or T, 첨부한 이미지와 같이 어떤 특징에 대해 두갈래로 나뉘어 지는데 이 특징을 type으로 놓는게 더 간편하지 않을까 싶습니다. 그리고 말씀해주신 데이터 구조에서는 mbtiType과 answer 내의 key가 중복됩니다

**Comment by rebi13** [comment]
@MCprotein 
넵 해당 구조로 진행해도 좋을 것 같습니다.
추가적으로, `"type": "energy_direction"` 부분은 제외해도 될 것 같습니다.
-> answer 배열에서 가중치(proportion)가 높은 요소의 객체를 해당 유형을 결정하는 문항으로 인식하기 때문입니다.

예를 들어 E / I 문항에 대한 유형을 계산하려고 할 때 4문항을 검사합니다.
1. E 60 / I 40 -> E유형 결정 문항 /  I선택
2. E 82 / I 18 -> E유형 결정 문항 / I선택
3. E 25 / I 75 -> I유형 결정 문항 / E선택
4. E 13 / I 87 -> I유형 결정 문항 / I선택

해당 경우에는 E점수가 25, I점수가 145점.
그러면 I점수가 더 높으니 I유형이 선택될 것입니다.

계산식은 큰 점수 / (작은점수 + 큰점수) * 100으로 비율이 정해질 것입니다.

위 결과를 예로 들면 145 / (25 + 145) = 145 / 170 = 0.85 .......... => I 85%

해당 계산식대로 진행하면 되기 때문에 말씀하신 대로 데이터 구조를 만들면 될 것 같습니다.

-----

프론트에서는 E나 I 같은 유형을 key로 사용할 수도 있을 것 같습니다. (계산식 사용)

**Comment by MCprotein** [comment]
@rebi13 네 확인 감사합니다 
그럼 정리해주신거 참고하여 진행하겠습니다!

**Comment by MCprotein** [comment]
@rebi13 
결과는 아래 구조 어떠신가요?
그리고 혹시 camel case 선호하시면 말씀부탁드립니다
```js
{
    user_id: 'string',
    // 스냅샷 형태로 모든 문항 저장. 추후 문항이 변경되었을때도 사용자는 이전 본인의 선택을 현재 문항과 관련없이 조회 가능해야하기때문
    // 스냅샷 형태가 아니라면 추후 문항이 삭제되었을때 본인 기록 조회 불가
    results: [
      {
        subject_id: ObjectId,
        answer: 'string',
        proportion: 'number',
        select: 'string',
        type: 'string'
      }
    ],
    fianl_type: 'string',
    fianl_type_proportion: 'number'
  }
```

**Comment by MCprotein** [comment]
@rebi13 제가 착각했네요 4가지종류가 있어야될듯합니다

**Comment by rebi13** [comment]
@MCprotein 

camel 선호합니다. 가능하면 바꿔주시면 감사드리겠습니다!

result는 배열에 각 유형별 결과 객체를 표시하는 것으로 의도하셨다면 4가지 종류가 있어야 하는 것이 맞습니다. (E,I / S,N / T,F / J,P)
result 배열에서의 객체의 각 요소에 대해서도 주석을 달아주실 수 있으실까요?

final type은 ISTJ, ESFP 등의 타입을 말씀하시는 것 같습니다.
final type proportion은 어떤 데이터를 의미하시는 것인지 알 수 있을까요?

![스크린샷 2024-04-28 21 47 56](https://github.com/MBTI-Inside/todo/assets/63568239/f9f6eceb-7dd5-45ef-9db4-bd5ec61e5636)

해당 사진은 이전 프로젝트에서 진행했던 결과 json mock 데이터입니다.
https://github.com/are-you-T/server/blob/main/testResult.json

참고만 해 주시면 좋을 것 같아요.



프론트에서 테스트 검사 선택 데이터를 말아서 보낼 때 어떠한 형태로 body data를 만들어 api 요청을 하면 될지도 같이 작성해주시면 감사드리겠습니다.

**Comment by MCprotein** [comment]
@rebi13 
제가 MBTI 결과를 잘못 생각하고 있었네요 예시 감사합니다 
궁합 좋은 mbti, 나쁜 mbti가 사람에 따라 다른게 아니라 각 mbti 마다 다른거라면 다른 collection에 저장하고 그 document id를 결과 document에 포함시키는게 좋을거같습니다
아래 구조 확인부탁드립니다!
```js
// compatibility collection
{
  id: 'abc123',
  type: 'good',
  mbti: 'ISFJ',
  targetMbti: 'ESFJ',
  description: 'ESFJ와 ISFJ는 둘 다 센서적이고 감정 중심의 유형이'
}
{
  id: 'abc124',
  type: 'bad',
  mbti: 'ISFJ',
  targetMbti: 'ENTP',
  description: 'ISFJ는 감정 중심이고 안정적인 관계를 선호하지만'
}

//
{
  mbti: 'ISFJ',
  summary: '용감한 수호자',
  tags: [],
  description: 'ISFJ 유형은 책임감이 강하고 온정적이며 헌신적입니다.',
  goodCompatibilityId: 'abc123',
  goodCompatibilityType: 'abc124',
  energy: [
    {
      type: 'I',
      proportion: 0.75
    },
    {
      type: 'E',
      proportion: 0.25
    }
  ],
  awareness: [
    {
      type: 'S',
      proportion: 0.75
    },
    {
      type: 'N',
      proportion: 0.25
    }
  ],
  judgement: [
    {
      type: 'F',
      proportion: 0.75
    },
    {
      type: 'T',
      proportion: 0.25
    }
  ],
  life: [
    {
      type: 'J',
      proportion: 0.75
    },
    {
      type: 'P',
      proportion: 0.25
    }
  ]
}
}
```

api docs는 고민중인데 postman으로 하면 어떨까요?
https://documenter.getpostman.com/view/18052446/2sA3JDhR1z

**Comment by rebi13** [comment]
@MCprotein 
구조 확인했습니다. 해당 형태로 진행되면 좋을 것 같습니다!
api docs는 무엇이든 상관 없을 것 같습니다. postman으로 진행하시죠!

**Comment by rebi13** [comment]
테스트 문항은 #4 에서 조회할 수 있도록 처리하였음.
