### ISSUE TITLE
전역적 Error 처리 (Error Boundary)

### ISSUE THREAD

**Issue by rebi13** [MBTI-Inside/todo#8]
최상위 컴포넌트에서 Error Boundary를 사용하고, axios 요청을 수행하는 컴포넌트에서도 에러를 처리할 수 있도록 설정합니다.

- MBTI-Inside/todo#7 과 연결되는 내용

**Comment by rebi13** [comment]
https://www.npmjs.com/package/react-error-boundary

**Comment by rebi13** [comment]
@MCprotein 

혹시 여러 종류의 에러중 하나의 에러를 랜덤으로 반환하는 API 추가 요청드려도 될까요?
에러 처리 테스트를 위해 필요할 것 같습니다.

**Comment by MCprotein** [comment]
@rebi13 늦어서 죄송합니다
완전 랜덤보다는 query string 으로 status code 입력한거에 따라 response status 가 결정되도록 /health api에 추가했습니다
ex) /heatlh?status=404
