### ISSUE TITLE
CORS 정책 위반 문제 해결

### ISSUE THREAD

**Issue by rebi13** [MBTI-Inside/todo#9]
![image](https://github.com/MBTI-Inside/todo/assets/63568239/be697d76-a012-4ff3-b42e-932269e745bc)

![image](https://github.com/MBTI-Inside/todo/assets/63568239/d9f09b18-60cd-47f4-94cd-12ba16e426d1)

![image](https://github.com/MBTI-Inside/todo/assets/63568239/d763e8f8-bf6a-479b-a7a1-cc989976b132)

branch 참조
https://github.com/MBTI-Inside/client/tree/feature/MBTI-Inisde/todo%234

client 폴더 내에서 `npm install` -> 환경 변수 설정(api endpoint) -> `npm run dev` 실행

.env 파일에 환경변수명은 `VITE_API_URL` 입니다.

실행 후 localhost:5173/question 페이지에 접근합니다.
![스크린샷 2024-06-15 10 41 32](https://github.com/MBTI-Inside/todo/assets/63568239/09054f1c-a966-44bb-adee-7acbb29509e0)

+ 버튼을 클릭하여 post 요청을 테스트할 수 있습니다.

src/pages/Question/index.tsx 파일에 api 호출 샘플이 있어 해당 페이지에서도 여러 테스트를 진행할 수 있습니다. (question 페이지)

**Comment by MCprotein** [comment]
@rebi13 넵 수정 완료 했습니다 확인부탁드립니다
## 원인
- application, api gateway 모두 cors 허용 설정을 해야되는데 누락

## 해결방법
아래 설정을 application, infra에 모두 적용
```js
origin: [process.env.CLIENT_HOST],
    credentials: true,
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH', 'HEAD'],
    allowedHeaders: [
      'Content-Type',
      'Authorization',
      'X-Requested-With',
      'X-HTTP-Method-Override',
      'X-Forwarded-Proto',
      'X-Forwarded-For',
      'X-Forwarded-Port'
    ],
```
그리고 preflight 캐시 시간은 300초로 지정해놨습니다

## 참고사항
- get, post, put은 requestAxios 함수 정상작동 확인했는데 delete는 cors 에러가 계속 발생합니다. axios.delete로 요청시 정상작동하니 이부분만 따로 확인부탁드립니다

**Comment by rebi13** [comment]
requestAxios 함수로 delete 요청 시 정상 작동됩니다. 감사합니다.
put요청은 아직 진행해보지 않아, 마저 크로스 체크 하고 이슈 닫도록 하겠습니다.

**Comment by rebi13** [comment]
put요청 정상 작동됩니다.
CRUD 정상 작동 확인되었으며 이슈 닫겠습니다.

수고 많으셨습니다!
